/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "url": "https://Gamefam.github.io",
  "projectName": "Inventory System",
  "favicon": "img/favicon.ico",
  "organizationName": "GameFam",
  "title": "Inventory System",
  "baseUrl": "/InventorySystem/",
  "tagline": "Cool tagline!",
  "themeConfig": {
    "prism": {
      "additionalLanguages": [
        "lua",
        "powershell"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "navbar": {
      "title": "Inventory System",
      "items": [
        {
          "type": "doc",
          "to": "/docs",
          "docId": "About",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "/api/",
          "label": "API",
          "position": "left"
        },
        {
          "href": "https://github.com/Gamefam/InventorySystem",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2023 GameFam. Built with Moonwave and Docusaurus. Developed by First , Second, Third and Fourth",
      "links": []
    },
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    [
      "docusaurus-plugin-moonwave",
      {
        "id": "moonwave",
        "code": [
          "C:\\Users\\user\\Documents\\GameFam\\InventorySystem\\src"
        ],
        "sourceUrl": "https://github.com/Gamefam/InventorySystem/blob/master",
        "projectDir": "C:\\Users\\user\\Documents\\GameFam\\InventorySystem",
        "classOrder": [],
        "apiCategories": [],
        "binaryPath": "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\moonwave\\dist\\bin\\moonwave-extractor-1.0.1.exe"
      }
    ],
    "docusaurus-lunr-search"
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "blog": false,
        "docs": {
          "sidebarPath": "C:\\Users\\user\\Documents\\GameFam\\Docusaurus-MoonWave-Template\\sidebars.js"
        },
        "theme": {
          "customCss": [
            "src/css/moonwave.css"
          ]
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
